print("Введите 1 этап: ")
a1 = input()
print("Введите 2 этап: ")
a2 = input()
print("Введите 3 этап: ")
a3 = input()
print("Введите 4 этап: ")
a4 = input()
print("Введите 5 этап: ")
a5 = input()
print("Введите 6 этап: ")
a6 = input()

print(a1, a2, a3, a4, a5, a6, sep='=>')
